/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteRouteImport } from './routes/company/route'
import { Route as FreelancerRouteRouteImport } from './routes/freelancer/route'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as CompanyDashboardRouteImport } from './routes/company/dashboard'
import { Route as CompanyProfileRouteImport } from './routes/company/profile'
import { Route as FreelancerDashboardRouteImport } from './routes/freelancer/dashboard'
import { Route as FreelancerProfileRouteImport } from './routes/freelancer/profile'
import { Route as ProjectProjectIdRouteRouteImport } from './routes/project/$projectId/route'
import { Route as CompanyApplicationsIndexRouteImport } from './routes/company/applications/index'
import { Route as CompanyApplicationsApplicationIdRouteImport } from './routes/company/applications/$applicationId'
import { Route as CompanyProjectsIndexRouteImport } from './routes/company/projects/index'
import { Route as CompanyProjectsProjectIdRouteImport } from './routes/company/projects/$projectId'
import { Route as CompanyProjectsNewRouteImport } from './routes/company/projects/new'
import { Route as FreelancerApplicationsIndexRouteImport } from './routes/freelancer/applications/index'
import { Route as FreelancerApplicationsApplicationIdRouteImport } from './routes/freelancer/applications/$applicationId'
import { Route as FreelancerProjectsIndexRouteImport } from './routes/freelancer/projects/index'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as FreelancerProjectsProjectIdIndexRouteImport } from './routes/freelancer/projects/$projectId/index'
import { Route as CompanyProjectsProjectIdDisputesIndexRouteImport } from './routes/company/projects/$projectId/disputes/index'
import { Route as CompanyProjectsProjectIdDisputesDisputeIdRouteImport } from './routes/company/projects/$projectId/disputes/$disputeId'
import { Route as CompanyProjectsProjectIdMilestonesIndexRouteImport } from './routes/company/projects/$projectId/milestones/index'
import { Route as CompanyProjectsProjectIdMilestonesMilestoneIdRouteImport } from './routes/company/projects/$projectId/milestones/$milestoneId'
import { Route as CompanyProjectsProjectIdMilestonesNewRouteImport } from './routes/company/projects/$projectId/milestones/new'
import { Route as FreelancerProjectsProjectIdDisputesIndexRouteImport } from './routes/freelancer/projects/$projectId/disputes/index'
import { Route as FreelancerProjectsProjectIdDisputesDisputeIdRouteImport } from './routes/freelancer/projects/$projectId/disputes/$disputeId'
import { Route as FreelancerProjectsProjectIdMilestonesIndexRouteImport } from './routes/freelancer/projects/$projectId/milestones/index'
import { Route as FreelancerProjectsProjectIdMilestonesMilestoneIdRouteImport } from './routes/freelancer/projects/$projectId/milestones/$milestoneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRouteRoute = CompanyRouteRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerRouteRoute = FreelancerRouteRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const FreelancerDashboardRoute = FreelancerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FreelancerRouteRoute,
} as any)
const FreelancerProfileRoute = FreelancerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FreelancerRouteRoute,
} as any)
const ProjectProjectIdRouteRoute = ProjectProjectIdRouteRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyApplicationsIndexRoute =
  CompanyApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => CompanyRouteRoute,
  } as any)
const CompanyApplicationsApplicationIdRoute =
  CompanyApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => CompanyRouteRoute,
  } as any)
const CompanyProjectsIndexRoute = CompanyProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const CompanyProjectsProjectIdRoute =
  CompanyProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => CompanyRouteRoute,
  } as any)
const CompanyProjectsNewRoute = CompanyProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => CompanyRouteRoute,
} as any)
const FreelancerApplicationsIndexRoute =
  FreelancerApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => FreelancerRouteRoute,
  } as any)
const FreelancerApplicationsApplicationIdRoute =
  FreelancerApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => FreelancerRouteRoute,
  } as any)
const FreelancerProjectsIndexRoute = FreelancerProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => FreelancerRouteRoute,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRouteRoute,
} as any)
const FreelancerProjectsProjectIdIndexRoute =
  FreelancerProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => FreelancerRouteRoute,
  } as any)
const CompanyProjectsProjectIdDisputesIndexRoute =
  CompanyProjectsProjectIdDisputesIndexRouteImport.update({
    id: '/disputes/',
    path: '/disputes/',
    getParentRoute: () => CompanyProjectsProjectIdRoute,
  } as any)
const CompanyProjectsProjectIdDisputesDisputeIdRoute =
  CompanyProjectsProjectIdDisputesDisputeIdRouteImport.update({
    id: '/disputes/$disputeId',
    path: '/disputes/$disputeId',
    getParentRoute: () => CompanyProjectsProjectIdRoute,
  } as any)
const CompanyProjectsProjectIdMilestonesIndexRoute =
  CompanyProjectsProjectIdMilestonesIndexRouteImport.update({
    id: '/milestones/',
    path: '/milestones/',
    getParentRoute: () => CompanyProjectsProjectIdRoute,
  } as any)
const CompanyProjectsProjectIdMilestonesMilestoneIdRoute =
  CompanyProjectsProjectIdMilestonesMilestoneIdRouteImport.update({
    id: '/milestones/$milestoneId',
    path: '/milestones/$milestoneId',
    getParentRoute: () => CompanyProjectsProjectIdRoute,
  } as any)
const CompanyProjectsProjectIdMilestonesNewRoute =
  CompanyProjectsProjectIdMilestonesNewRouteImport.update({
    id: '/milestones/new',
    path: '/milestones/new',
    getParentRoute: () => CompanyProjectsProjectIdRoute,
  } as any)
const FreelancerProjectsProjectIdDisputesIndexRoute =
  FreelancerProjectsProjectIdDisputesIndexRouteImport.update({
    id: '/projects/$projectId/disputes/',
    path: '/projects/$projectId/disputes/',
    getParentRoute: () => FreelancerRouteRoute,
  } as any)
const FreelancerProjectsProjectIdDisputesDisputeIdRoute =
  FreelancerProjectsProjectIdDisputesDisputeIdRouteImport.update({
    id: '/projects/$projectId/disputes/$disputeId',
    path: '/projects/$projectId/disputes/$disputeId',
    getParentRoute: () => FreelancerRouteRoute,
  } as any)
const FreelancerProjectsProjectIdMilestonesIndexRoute =
  FreelancerProjectsProjectIdMilestonesIndexRouteImport.update({
    id: '/projects/$projectId/milestones/',
    path: '/projects/$projectId/milestones/',
    getParentRoute: () => FreelancerRouteRoute,
  } as any)
const FreelancerProjectsProjectIdMilestonesMilestoneIdRoute =
  FreelancerProjectsProjectIdMilestonesMilestoneIdRouteImport.update({
    id: '/projects/$projectId/milestones/$milestoneId',
    path: '/projects/$projectId/milestones/$milestoneId',
    getParentRoute: () => FreelancerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteRouteWithChildren
  '/freelancer': typeof FreelancerRouteRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/profile': typeof CompanyProfileRoute
  '/freelancer/dashboard': typeof FreelancerDashboardRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/company/applications/$applicationId': typeof CompanyApplicationsApplicationIdRoute
  '/company/projects/$projectId': typeof CompanyProjectsProjectIdRouteWithChildren
  '/company/projects/new': typeof CompanyProjectsNewRoute
  '/freelancer/applications/$applicationId': typeof FreelancerApplicationsApplicationIdRoute
  '/company/applications/': typeof CompanyApplicationsIndexRoute
  '/company/projects/': typeof CompanyProjectsIndexRoute
  '/freelancer/applications/': typeof FreelancerApplicationsIndexRoute
  '/freelancer/projects/': typeof FreelancerProjectsIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/freelancer/projects/$projectId/': typeof FreelancerProjectsProjectIdIndexRoute
  '/company/projects/$projectId/disputes/$disputeId': typeof CompanyProjectsProjectIdDisputesDisputeIdRoute
  '/company/projects/$projectId/milestones/$milestoneId': typeof CompanyProjectsProjectIdMilestonesMilestoneIdRoute
  '/company/projects/$projectId/milestones/new': typeof CompanyProjectsProjectIdMilestonesNewRoute
  '/freelancer/projects/$projectId/disputes/$disputeId': typeof FreelancerProjectsProjectIdDisputesDisputeIdRoute
  '/freelancer/projects/$projectId/milestones/$milestoneId': typeof FreelancerProjectsProjectIdMilestonesMilestoneIdRoute
  '/company/projects/$projectId/disputes/': typeof CompanyProjectsProjectIdDisputesIndexRoute
  '/company/projects/$projectId/milestones/': typeof CompanyProjectsProjectIdMilestonesIndexRoute
  '/freelancer/projects/$projectId/disputes/': typeof FreelancerProjectsProjectIdDisputesIndexRoute
  '/freelancer/projects/$projectId/milestones/': typeof FreelancerProjectsProjectIdMilestonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteRouteWithChildren
  '/freelancer': typeof FreelancerRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/profile': typeof CompanyProfileRoute
  '/freelancer/dashboard': typeof FreelancerDashboardRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/company/applications/$applicationId': typeof CompanyApplicationsApplicationIdRoute
  '/company/projects/$projectId': typeof CompanyProjectsProjectIdRouteWithChildren
  '/company/projects/new': typeof CompanyProjectsNewRoute
  '/freelancer/applications/$applicationId': typeof FreelancerApplicationsApplicationIdRoute
  '/company/applications': typeof CompanyApplicationsIndexRoute
  '/company/projects': typeof CompanyProjectsIndexRoute
  '/freelancer/applications': typeof FreelancerApplicationsIndexRoute
  '/freelancer/projects': typeof FreelancerProjectsIndexRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/freelancer/projects/$projectId': typeof FreelancerProjectsProjectIdIndexRoute
  '/company/projects/$projectId/disputes/$disputeId': typeof CompanyProjectsProjectIdDisputesDisputeIdRoute
  '/company/projects/$projectId/milestones/$milestoneId': typeof CompanyProjectsProjectIdMilestonesMilestoneIdRoute
  '/company/projects/$projectId/milestones/new': typeof CompanyProjectsProjectIdMilestonesNewRoute
  '/freelancer/projects/$projectId/disputes/$disputeId': typeof FreelancerProjectsProjectIdDisputesDisputeIdRoute
  '/freelancer/projects/$projectId/milestones/$milestoneId': typeof FreelancerProjectsProjectIdMilestonesMilestoneIdRoute
  '/company/projects/$projectId/disputes': typeof CompanyProjectsProjectIdDisputesIndexRoute
  '/company/projects/$projectId/milestones': typeof CompanyProjectsProjectIdMilestonesIndexRoute
  '/freelancer/projects/$projectId/disputes': typeof FreelancerProjectsProjectIdDisputesIndexRoute
  '/freelancer/projects/$projectId/milestones': typeof FreelancerProjectsProjectIdMilestonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteRouteWithChildren
  '/freelancer': typeof FreelancerRouteRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/profile': typeof CompanyProfileRoute
  '/freelancer/dashboard': typeof FreelancerDashboardRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/company/applications/$applicationId': typeof CompanyApplicationsApplicationIdRoute
  '/company/projects/$projectId': typeof CompanyProjectsProjectIdRouteWithChildren
  '/company/projects/new': typeof CompanyProjectsNewRoute
  '/freelancer/applications/$applicationId': typeof FreelancerApplicationsApplicationIdRoute
  '/company/applications/': typeof CompanyApplicationsIndexRoute
  '/company/projects/': typeof CompanyProjectsIndexRoute
  '/freelancer/applications/': typeof FreelancerApplicationsIndexRoute
  '/freelancer/projects/': typeof FreelancerProjectsIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/freelancer/projects/$projectId/': typeof FreelancerProjectsProjectIdIndexRoute
  '/company/projects/$projectId/disputes/$disputeId': typeof CompanyProjectsProjectIdDisputesDisputeIdRoute
  '/company/projects/$projectId/milestones/$milestoneId': typeof CompanyProjectsProjectIdMilestonesMilestoneIdRoute
  '/company/projects/$projectId/milestones/new': typeof CompanyProjectsProjectIdMilestonesNewRoute
  '/freelancer/projects/$projectId/disputes/$disputeId': typeof FreelancerProjectsProjectIdDisputesDisputeIdRoute
  '/freelancer/projects/$projectId/milestones/$milestoneId': typeof FreelancerProjectsProjectIdMilestonesMilestoneIdRoute
  '/company/projects/$projectId/disputes/': typeof CompanyProjectsProjectIdDisputesIndexRoute
  '/company/projects/$projectId/milestones/': typeof CompanyProjectsProjectIdMilestonesIndexRoute
  '/freelancer/projects/$projectId/disputes/': typeof FreelancerProjectsProjectIdDisputesIndexRoute
  '/freelancer/projects/$projectId/milestones/': typeof FreelancerProjectsProjectIdMilestonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/freelancer'
    | '/project/$projectId'
    | '/auth/login'
    | '/company/dashboard'
    | '/company/profile'
    | '/freelancer/dashboard'
    | '/freelancer/profile'
    | '/company/applications/$applicationId'
    | '/company/projects/$projectId'
    | '/company/projects/new'
    | '/freelancer/applications/$applicationId'
    | '/company/applications/'
    | '/company/projects/'
    | '/freelancer/applications/'
    | '/freelancer/projects/'
    | '/project/$projectId/'
    | '/freelancer/projects/$projectId/'
    | '/company/projects/$projectId/disputes/$disputeId'
    | '/company/projects/$projectId/milestones/$milestoneId'
    | '/company/projects/$projectId/milestones/new'
    | '/freelancer/projects/$projectId/disputes/$disputeId'
    | '/freelancer/projects/$projectId/milestones/$milestoneId'
    | '/company/projects/$projectId/disputes/'
    | '/company/projects/$projectId/milestones/'
    | '/freelancer/projects/$projectId/disputes/'
    | '/freelancer/projects/$projectId/milestones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/freelancer'
    | '/auth/login'
    | '/company/dashboard'
    | '/company/profile'
    | '/freelancer/dashboard'
    | '/freelancer/profile'
    | '/company/applications/$applicationId'
    | '/company/projects/$projectId'
    | '/company/projects/new'
    | '/freelancer/applications/$applicationId'
    | '/company/applications'
    | '/company/projects'
    | '/freelancer/applications'
    | '/freelancer/projects'
    | '/project/$projectId'
    | '/freelancer/projects/$projectId'
    | '/company/projects/$projectId/disputes/$disputeId'
    | '/company/projects/$projectId/milestones/$milestoneId'
    | '/company/projects/$projectId/milestones/new'
    | '/freelancer/projects/$projectId/disputes/$disputeId'
    | '/freelancer/projects/$projectId/milestones/$milestoneId'
    | '/company/projects/$projectId/disputes'
    | '/company/projects/$projectId/milestones'
    | '/freelancer/projects/$projectId/disputes'
    | '/freelancer/projects/$projectId/milestones'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/freelancer'
    | '/project/$projectId'
    | '/auth/login'
    | '/company/dashboard'
    | '/company/profile'
    | '/freelancer/dashboard'
    | '/freelancer/profile'
    | '/company/applications/$applicationId'
    | '/company/projects/$projectId'
    | '/company/projects/new'
    | '/freelancer/applications/$applicationId'
    | '/company/applications/'
    | '/company/projects/'
    | '/freelancer/applications/'
    | '/freelancer/projects/'
    | '/project/$projectId/'
    | '/freelancer/projects/$projectId/'
    | '/company/projects/$projectId/disputes/$disputeId'
    | '/company/projects/$projectId/milestones/$milestoneId'
    | '/company/projects/$projectId/milestones/new'
    | '/freelancer/projects/$projectId/disputes/$disputeId'
    | '/freelancer/projects/$projectId/milestones/$milestoneId'
    | '/company/projects/$projectId/disputes/'
    | '/company/projects/$projectId/milestones/'
    | '/freelancer/projects/$projectId/disputes/'
    | '/freelancer/projects/$projectId/milestones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRouteRoute: typeof CompanyRouteRouteWithChildren
  FreelancerRouteRoute: typeof FreelancerRouteRouteWithChildren
  ProjectProjectIdRouteRoute: typeof ProjectProjectIdRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer': {
      id: '/freelancer'
      path: '/freelancer'
      fullPath: '/freelancer'
      preLoaderRoute: typeof FreelancerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/dashboard': {
      id: '/company/dashboard'
      path: '/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/company/profile': {
      id: '/company/profile'
      path: '/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/freelancer/dashboard': {
      id: '/freelancer/dashboard'
      path: '/dashboard'
      fullPath: '/freelancer/dashboard'
      preLoaderRoute: typeof FreelancerDashboardRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
    '/freelancer/profile': {
      id: '/freelancer/profile'
      path: '/profile'
      fullPath: '/freelancer/profile'
      preLoaderRoute: typeof FreelancerProfileRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/applications/': {
      id: '/company/applications/'
      path: '/applications'
      fullPath: '/company/applications/'
      preLoaderRoute: typeof CompanyApplicationsIndexRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/company/applications/$applicationId': {
      id: '/company/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/company/applications/$applicationId'
      preLoaderRoute: typeof CompanyApplicationsApplicationIdRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/company/projects/': {
      id: '/company/projects/'
      path: '/projects'
      fullPath: '/company/projects/'
      preLoaderRoute: typeof CompanyProjectsIndexRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/company/projects/$projectId': {
      id: '/company/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/company/projects/$projectId'
      preLoaderRoute: typeof CompanyProjectsProjectIdRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/company/projects/new': {
      id: '/company/projects/new'
      path: '/projects/new'
      fullPath: '/company/projects/new'
      preLoaderRoute: typeof CompanyProjectsNewRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    '/freelancer/applications/': {
      id: '/freelancer/applications/'
      path: '/applications'
      fullPath: '/freelancer/applications/'
      preLoaderRoute: typeof FreelancerApplicationsIndexRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
    '/freelancer/applications/$applicationId': {
      id: '/freelancer/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/freelancer/applications/$applicationId'
      preLoaderRoute: typeof FreelancerApplicationsApplicationIdRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
    '/freelancer/projects/': {
      id: '/freelancer/projects/'
      path: '/projects'
      fullPath: '/freelancer/projects/'
      preLoaderRoute: typeof FreelancerProjectsIndexRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRouteRoute
    }
    '/freelancer/projects/$projectId/': {
      id: '/freelancer/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/freelancer/projects/$projectId/'
      preLoaderRoute: typeof FreelancerProjectsProjectIdIndexRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
    '/company/projects/$projectId/disputes/': {
      id: '/company/projects/$projectId/disputes/'
      path: '/disputes'
      fullPath: '/company/projects/$projectId/disputes/'
      preLoaderRoute: typeof CompanyProjectsProjectIdDisputesIndexRouteImport
      parentRoute: typeof CompanyProjectsProjectIdRoute
    }
    '/company/projects/$projectId/disputes/$disputeId': {
      id: '/company/projects/$projectId/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/company/projects/$projectId/disputes/$disputeId'
      preLoaderRoute: typeof CompanyProjectsProjectIdDisputesDisputeIdRouteImport
      parentRoute: typeof CompanyProjectsProjectIdRoute
    }
    '/company/projects/$projectId/milestones/': {
      id: '/company/projects/$projectId/milestones/'
      path: '/milestones'
      fullPath: '/company/projects/$projectId/milestones/'
      preLoaderRoute: typeof CompanyProjectsProjectIdMilestonesIndexRouteImport
      parentRoute: typeof CompanyProjectsProjectIdRoute
    }
    '/company/projects/$projectId/milestones/$milestoneId': {
      id: '/company/projects/$projectId/milestones/$milestoneId'
      path: '/milestones/$milestoneId'
      fullPath: '/company/projects/$projectId/milestones/$milestoneId'
      preLoaderRoute: typeof CompanyProjectsProjectIdMilestonesMilestoneIdRouteImport
      parentRoute: typeof CompanyProjectsProjectIdRoute
    }
    '/company/projects/$projectId/milestones/new': {
      id: '/company/projects/$projectId/milestones/new'
      path: '/milestones/new'
      fullPath: '/company/projects/$projectId/milestones/new'
      preLoaderRoute: typeof CompanyProjectsProjectIdMilestonesNewRouteImport
      parentRoute: typeof CompanyProjectsProjectIdRoute
    }
    '/freelancer/projects/$projectId/disputes/': {
      id: '/freelancer/projects/$projectId/disputes/'
      path: '/projects/$projectId/disputes'
      fullPath: '/freelancer/projects/$projectId/disputes/'
      preLoaderRoute: typeof FreelancerProjectsProjectIdDisputesIndexRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
    '/freelancer/projects/$projectId/disputes/$disputeId': {
      id: '/freelancer/projects/$projectId/disputes/$disputeId'
      path: '/projects/$projectId/disputes/$disputeId'
      fullPath: '/freelancer/projects/$projectId/disputes/$disputeId'
      preLoaderRoute: typeof FreelancerProjectsProjectIdDisputesDisputeIdRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
    '/freelancer/projects/$projectId/milestones/': {
      id: '/freelancer/projects/$projectId/milestones/'
      path: '/projects/$projectId/milestones'
      fullPath: '/freelancer/projects/$projectId/milestones/'
      preLoaderRoute: typeof FreelancerProjectsProjectIdMilestonesIndexRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
    '/freelancer/projects/$projectId/milestones/$milestoneId': {
      id: '/freelancer/projects/$projectId/milestones/$milestoneId'
      path: '/projects/$projectId/milestones/$milestoneId'
      fullPath: '/freelancer/projects/$projectId/milestones/$milestoneId'
      preLoaderRoute: typeof FreelancerProjectsProjectIdMilestonesMilestoneIdRouteImport
      parentRoute: typeof FreelancerRouteRoute
    }
  }
}

interface CompanyProjectsProjectIdRouteChildren {
  CompanyProjectsProjectIdDisputesDisputeIdRoute: typeof CompanyProjectsProjectIdDisputesDisputeIdRoute
  CompanyProjectsProjectIdMilestonesMilestoneIdRoute: typeof CompanyProjectsProjectIdMilestonesMilestoneIdRoute
  CompanyProjectsProjectIdMilestonesNewRoute: typeof CompanyProjectsProjectIdMilestonesNewRoute
  CompanyProjectsProjectIdDisputesIndexRoute: typeof CompanyProjectsProjectIdDisputesIndexRoute
  CompanyProjectsProjectIdMilestonesIndexRoute: typeof CompanyProjectsProjectIdMilestonesIndexRoute
}

const CompanyProjectsProjectIdRouteChildren: CompanyProjectsProjectIdRouteChildren =
  {
    CompanyProjectsProjectIdDisputesDisputeIdRoute:
      CompanyProjectsProjectIdDisputesDisputeIdRoute,
    CompanyProjectsProjectIdMilestonesMilestoneIdRoute:
      CompanyProjectsProjectIdMilestonesMilestoneIdRoute,
    CompanyProjectsProjectIdMilestonesNewRoute:
      CompanyProjectsProjectIdMilestonesNewRoute,
    CompanyProjectsProjectIdDisputesIndexRoute:
      CompanyProjectsProjectIdDisputesIndexRoute,
    CompanyProjectsProjectIdMilestonesIndexRoute:
      CompanyProjectsProjectIdMilestonesIndexRoute,
  }

const CompanyProjectsProjectIdRouteWithChildren =
  CompanyProjectsProjectIdRoute._addFileChildren(
    CompanyProjectsProjectIdRouteChildren,
  )

interface CompanyRouteRouteChildren {
  CompanyDashboardRoute: typeof CompanyDashboardRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  CompanyApplicationsApplicationIdRoute: typeof CompanyApplicationsApplicationIdRoute
  CompanyProjectsProjectIdRoute: typeof CompanyProjectsProjectIdRouteWithChildren
  CompanyProjectsNewRoute: typeof CompanyProjectsNewRoute
  CompanyApplicationsIndexRoute: typeof CompanyApplicationsIndexRoute
  CompanyProjectsIndexRoute: typeof CompanyProjectsIndexRoute
}

const CompanyRouteRouteChildren: CompanyRouteRouteChildren = {
  CompanyDashboardRoute: CompanyDashboardRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  CompanyApplicationsApplicationIdRoute: CompanyApplicationsApplicationIdRoute,
  CompanyProjectsProjectIdRoute: CompanyProjectsProjectIdRouteWithChildren,
  CompanyProjectsNewRoute: CompanyProjectsNewRoute,
  CompanyApplicationsIndexRoute: CompanyApplicationsIndexRoute,
  CompanyProjectsIndexRoute: CompanyProjectsIndexRoute,
}

const CompanyRouteRouteWithChildren = CompanyRouteRoute._addFileChildren(
  CompanyRouteRouteChildren,
)

interface FreelancerRouteRouteChildren {
  FreelancerDashboardRoute: typeof FreelancerDashboardRoute
  FreelancerProfileRoute: typeof FreelancerProfileRoute
  FreelancerApplicationsApplicationIdRoute: typeof FreelancerApplicationsApplicationIdRoute
  FreelancerApplicationsIndexRoute: typeof FreelancerApplicationsIndexRoute
  FreelancerProjectsIndexRoute: typeof FreelancerProjectsIndexRoute
  FreelancerProjectsProjectIdIndexRoute: typeof FreelancerProjectsProjectIdIndexRoute
  FreelancerProjectsProjectIdDisputesDisputeIdRoute: typeof FreelancerProjectsProjectIdDisputesDisputeIdRoute
  FreelancerProjectsProjectIdMilestonesMilestoneIdRoute: typeof FreelancerProjectsProjectIdMilestonesMilestoneIdRoute
  FreelancerProjectsProjectIdDisputesIndexRoute: typeof FreelancerProjectsProjectIdDisputesIndexRoute
  FreelancerProjectsProjectIdMilestonesIndexRoute: typeof FreelancerProjectsProjectIdMilestonesIndexRoute
}

const FreelancerRouteRouteChildren: FreelancerRouteRouteChildren = {
  FreelancerDashboardRoute: FreelancerDashboardRoute,
  FreelancerProfileRoute: FreelancerProfileRoute,
  FreelancerApplicationsApplicationIdRoute:
    FreelancerApplicationsApplicationIdRoute,
  FreelancerApplicationsIndexRoute: FreelancerApplicationsIndexRoute,
  FreelancerProjectsIndexRoute: FreelancerProjectsIndexRoute,
  FreelancerProjectsProjectIdIndexRoute: FreelancerProjectsProjectIdIndexRoute,
  FreelancerProjectsProjectIdDisputesDisputeIdRoute:
    FreelancerProjectsProjectIdDisputesDisputeIdRoute,
  FreelancerProjectsProjectIdMilestonesMilestoneIdRoute:
    FreelancerProjectsProjectIdMilestonesMilestoneIdRoute,
  FreelancerProjectsProjectIdDisputesIndexRoute:
    FreelancerProjectsProjectIdDisputesIndexRoute,
  FreelancerProjectsProjectIdMilestonesIndexRoute:
    FreelancerProjectsProjectIdMilestonesIndexRoute,
}

const FreelancerRouteRouteWithChildren = FreelancerRouteRoute._addFileChildren(
  FreelancerRouteRouteChildren,
)

interface ProjectProjectIdRouteRouteChildren {
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteRouteChildren: ProjectProjectIdRouteRouteChildren = {
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteRouteWithChildren =
  ProjectProjectIdRouteRoute._addFileChildren(
    ProjectProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRouteRoute: CompanyRouteRouteWithChildren,
  FreelancerRouteRoute: FreelancerRouteRouteWithChildren,
  ProjectProjectIdRouteRoute: ProjectProjectIdRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
